# Generated by Django 5.1.2 on 2024-11-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
